
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'initARROW COLON EPSILON EQUALS NEWLINE NON_TERMINAL PIPE PROGRAM REGEX TERMINALinit : program newlines lista_regras token_sectionprogram : PROGRAM COLON NON_TERMINALlista_regras : regra lista_regraslista_regras : regra : NON_TERMINAL ARROW lista_producoes newlinesregra : NON_TERMINAL ARROW lista_producoeslista_producoes : producao lista_producoes_restlista_producoes_rest : PIPE producao lista_producoes_restlista_producoes_rest : producao : simbolo lista_simboloslista_simbolos : simbolo lista_simboloslista_simbolos : simbolo : EPSILONsimbolo : TERMINALsimbolo : NON_TERMINALtoken_section : token_decl token_sectiontoken_section : token_decl : TERMINAL EQUALS REGEX newlinestoken_decl : TERMINAL EQUALS REGEXnewlines : NEWLINE\n               | NEWLINE newlines'
    
_lr_action_items = {'PROGRAM':([0,],[3,]),'$end':([1,4,5,7,8,10,12,13,15,17,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,],[0,-4,-20,-17,-4,-21,-1,-17,-3,-16,-15,-6,-9,-12,-13,-14,-19,-5,-7,-12,-10,-18,-9,-11,-8,]),'NEWLINE':([2,5,11,19,20,21,22,23,24,25,27,29,30,32,33,34,],[5,5,-2,-15,5,-9,-12,-13,-14,5,-7,-12,-10,-9,-11,-8,]),'COLON':([3,],[6,]),'TERMINAL':([4,5,7,8,10,13,15,16,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,],[-4,-20,14,-4,-21,14,-3,24,-15,-6,-9,24,-13,-14,-19,-5,-7,24,24,-10,-18,-9,-11,-8,]),'NON_TERMINAL':([4,5,6,8,10,16,19,20,21,22,23,24,26,27,28,29,30,32,33,34,],[9,-20,11,9,-21,19,-15,-6,-9,19,-13,-14,-5,-7,19,19,-10,-9,-11,-8,]),'ARROW':([9,],[16,]),'EQUALS':([14,],[18,]),'EPSILON':([16,19,22,23,24,28,29,],[23,-15,23,-13,-14,23,23,]),'REGEX':([18,],[25,]),'PIPE':([19,21,22,23,24,29,30,32,33,],[-15,28,-12,-13,-14,-12,-10,28,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'program':([0,],[2,]),'newlines':([2,5,20,25,],[4,10,26,31,]),'lista_regras':([4,8,],[7,15,]),'regra':([4,8,],[8,8,]),'token_section':([7,13,],[12,17,]),'token_decl':([7,13,],[13,13,]),'lista_producoes':([16,],[20,]),'producao':([16,28,],[21,32,]),'simbolo':([16,22,28,29,],[22,29,22,29,]),'lista_producoes_rest':([21,32,],[27,34,]),'lista_simbolos':([22,29,],[30,33,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> program newlines lista_regras token_section','init',4,'p_init','parser_grammar.py',10),
  ('program -> PROGRAM COLON NON_TERMINAL','program',3,'p_program','parser_grammar.py',15),
  ('lista_regras -> regra lista_regras','lista_regras',2,'p_lista_regras','parser_grammar.py',19),
  ('lista_regras -> <empty>','lista_regras',0,'p_lista_regras_empty','parser_grammar.py',25),
  ('regra -> NON_TERMINAL ARROW lista_producoes newlines','regra',4,'p_regra_newLine','parser_grammar.py',29),
  ('regra -> NON_TERMINAL ARROW lista_producoes','regra',3,'p_regra_sem_newLine','parser_grammar.py',34),
  ('lista_producoes -> producao lista_producoes_rest','lista_producoes',2,'p_lista_producoes','parser_grammar.py',39),
  ('lista_producoes_rest -> PIPE producao lista_producoes_rest','lista_producoes_rest',3,'p_lista_producoes_rest','parser_grammar.py',45),
  ('lista_producoes_rest -> <empty>','lista_producoes_rest',0,'p_lista_producoes_rest_empty','parser_grammar.py',51),
  ('producao -> simbolo lista_simbolos','producao',2,'p_producao','parser_grammar.py',55),
  ('lista_simbolos -> simbolo lista_simbolos','lista_simbolos',2,'p_lista_simbolos','parser_grammar.py',62),
  ('lista_simbolos -> <empty>','lista_simbolos',0,'p_lista_simbolos_empty','parser_grammar.py',67),
  ('simbolo -> EPSILON','simbolo',1,'p_simbolo_epsilon','parser_grammar.py',71),
  ('simbolo -> TERMINAL','simbolo',1,'p_simbolo_term','parser_grammar.py',76),
  ('simbolo -> NON_TERMINAL','simbolo',1,'p_simbolo_non_term','parser_grammar.py',81),
  ('token_section -> token_decl token_section','token_section',2,'p_token_section','parser_grammar.py',86),
  ('token_section -> <empty>','token_section',0,'p_token_section_empty','parser_grammar.py',91),
  ('token_decl -> TERMINAL EQUALS REGEX newlines','token_decl',4,'p_token_newline','parser_grammar.py',95),
  ('token_decl -> TERMINAL EQUALS REGEX','token_decl',3,'p_token_sem_newline','parser_grammar.py',102),
  ('newlines -> NEWLINE','newlines',1,'p_newlines','parser_grammar.py',108),
  ('newlines -> NEWLINE newlines','newlines',2,'p_newlines','parser_grammar.py',109),
]
